# for running with traefik
version: '3'

services:
  blog:
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=localhost
      - DB_PORT=5432
      - DOMAIN=https://example.com
      - SERVER_PORT=8080
    restart: always
    networks:
      - web
    container_name: blog
    labels:
      - "traefik.backend=blog"
      - "traefik.docker.network=web"
      - "traefik.port=8080"
      - "traefik.site.frontend.rule=Host:example.com"
      - "traefik.adminRobot.frontend.rule=Host:admin.example.com;Path:/robots.txt"
      - "traefik.admin.frontend.rule=Host:admin.example.com"
      - "traefik.admin.frontend.auth.basic.users=user1:hash,user2:hash"

networks:
  web:
    external: true
