listen:
  address: 0.0.0.0
  port: 3001
target:
  url: "http://127.0.0.1:8080"
backend:
  url: "http://127.0.0.1:8080"
headless:
  internal:
    url: "http://127.0.0.1:9222"
filters:
  userAgent:
    defaultPolicy: blacklist
    exceptions:
      keywords:
        - bot
        - slurp
        - bing
        - crawler