CREATE TABLE Users
(
  LOGIN    CHARACTER VARYING(36)  not null,
  EMAIL    CHARACTER VARYING(255) not null,
  PASSWORD CHARACTER VARYING(255) not null
);

CREATE UNIQUE INDEX login ON users (LOGIN);
CREATE UNIQUE INDEX login ON users (EMAIL);